import extractionDefaultSettings from "./possibleSettings/extraction/extractionDefaultSettings";

// Node parameters for Home module of extraction tab
const nodesParams = {
  input: {
    type: "inputNode",
    classes: "object input upload run",
    nbInput: 0,
    nbOutput: 1,
    input: [],
    output: ["segmentation"],
    img: "input.svg",
    title: "Input",
    possibleSettings: {},
  },
  segmentation: {
    type: "segmentationNode",
    classes: "object segmentation view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["input"],
    output: ["interpolation", "filter"],
    img: "segmentation.png",
    title: "Segmentation",
    possibleSettings: {},
  },
  interpolation: {
    type: "standardNode",
    classes: "object interpolation view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["segmentation"],
    output: ["re_segmentation"],
    img: "interpolation.png",
    title: "Interpolation",
    possibleSettings: {
      defaultSettings: extractionDefaultSettings.interpolation,
    },
  },
  filter: {
    type: "filterNode",
    classes: "object filter view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["segmentation", "re_segmentation"],
    output: ["roi_extraction", "extraction"],
    img: "filter.svg",
    title: "Filter",
    possibleSettings: {
      defaultSettings: extractionDefaultSettings.filter,
    },
  },
  re_segmentation: {
    type: "standardNode",
    classes: "object re_segmentation view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["interpolation"],
    output: ["roi_extraction", "filter", "extraction"],
    img: "segmentation.png",
    title: "Re-Segmentation",
    possibleSettings: {
      defaultSettings: extractionDefaultSettings.re_segmentation,
    },
  },
  roi_extraction: {
    type: "standardNode",
    classes: "object roi_extraction view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["re_segmentation", "filter"],
    output: ["discretization", "extraction"],
    img: "roi_extraction.png",
    title: "ROI extraction",
    possibleSettings: {},
  },
  discretization: {
    type: "standardNode",
    classes: "object discretization view run",
    nbInput: 1,
    nbOutput: 1,
    input: ["roi_extraction"],
    output: ["extraction"],
    img: "discretization.svg",
    title: "Discretization",
    possibleSettings: {
      defaultSettings: extractionDefaultSettings.discretization,
    },
  },
  extraction: {
    type: "standardNode",
    classes: "object extraction",
    nbInput: 1,
    nbOutput: 0,
    input: ["re_segmentation", "filter", "roi_extraction", "discretization"],
    output: [],
    img: "extraction.svg",
    title: "Extraction",
    possibleSettings: {},
  },
};

export default nodesParams;
