// Node parameters for Home module of extraction tab
const nodesParams = {
  input: {
    type: "inputNode",
    classes: "object input upload run",
    input: [],
    output: ["segmentation"],
    img: "inputs.svg.png",
    title: "Input",
    possibleSettings: {},
  },
  segmentation: {
    type: "standardNode",
    classes: "object segmentation view run",
    input: ["input"],
    output: ["interpolation, filter"],
    img: "segmentation.png",
    title: "Segmentation",
    possibleSettings: {},
  },
  interpolation: {
    type: "standardNode",
    classes: "object interpolation view run",
    input: ["segmentation"],
    output: ["re_segmentation"],
    img: "interpolation.png",
    title: "Interpolation",
    possibleSettings: {},
  },
  filter: {
    type: "standardNode",
    classes: "object filter view run",
    input: ["segmentation, re_segmentation"],
    output: ["roi_extraction, extraction"],
    img: "filter.png",
    title: "Filter",
    possibleSettings: {},
  },
  re_segmentation: {
    type: "standardNode",
    classes: "object re_segmentation view run",
    input: ["interpolation"],
    output: ["roi_extraction, filter, extraction"],
    img: "segmentation.png",
    title: "Segmentation",
    possibleSettings: {},
  },

  roi_extraction: {
    type: "standardNode",
    classes: "object roi_extraction view run",
    input: ["re_segmentation, filter"],
    output: ["discretization, extraction"],
    img: "roi_extraction.png",
    title: "ROI extraction",
    possibleSettings: {},
  },
  discretization: {
    type: "standardNode",
    classes: "object discretization view run",
    input: ["roi_extraction"],
    output: ["extraction"],
    img: "discretization.svg",
    title: "Discretization",
    possibleSettings: {},
  },
  re_segmentation: {
    type: "standardNode",
    classes: "object resegmentation view run",
    input: ["interpolation"],
    output: ["roi_extraction, filter, extraction"],
    img: "segmentation.png",
    title: "Re-segmentation",
    possibleSettings: {},
  },
  extraction: {
    type: "standardNode",
    classes: "object extraction",
    input: ["re_segmentation, filter, roi_extraction, discretization"],
    output: [],
    img: "extraction.png",
    title: "Extraction",
    possibleSettings: {},
  },
};

export default nodesParams;
