// Node parameters for Extraction module of extraction tab
const nodesParams = {
  morphological: {
    type: "featuresNode",
    classes: "object ntf morphological",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "MORPH",
    possibleSettings: {},
  },
  local_intensity: {
    type: "featuresNode",
    classes: "object ntf local_intensity",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "LI",
    possibleSettings: {},
  },
  statistical: {
    type: "featuresNode",
    classes: "object ntf statistical",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "IS, STAT",
    possibleSettings: {},
  },
  intensity_histogram: {
    type: "featuresNode",
    classes: "object ntf intensity_histogram",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "IH",
    possibleSettings: {},
  },
  ivh: {
    type: "featuresNode",
    classes: "object ntf ivh",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "IVH",
    possibleSettings: {},
  },
  glcm: {
    type: "featuresNode",
    classes: "object tf glcm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "GLCM",
    possibleSettings: {},
  },
  gldzm: {
    type: "featuresNode",
    classes: "object tf gldzm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "GLDZM",
    possibleSettings: {},
  },
  glcm: {
    type: "featuresNode",
    classes: "object tf glrlm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "GLRLM",
    possibleSettings: {},
  },
  glszm: {
    type: "featuresNode",
    classes: "object tf glszm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "GLSZM",
    possibleSettings: {},
  },
  ngldm: {
    type: "featuresNode",
    classes: "object tf ngldm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "NGLDM",
    possibleSettings: {},
  },
  ngtdm: {
    type: "featuresNode",
    classes: "object tf ngtdm",
    nbInput: 0,
    nbOutput: 0,
    img: "features.svg",
    title: "NGTDM",
    possibleSettings: {},
  },
};

export default nodesParams;
