from learning.MEDml.MEDexperiment import MEDexperiment
from flask import request, Blueprint
import json
from utils.server_utils import get_json_from_request, get_response_from_error
import os
from pathlib import Path
import copy

MEDOMICS_WS = str(Path(os.path.dirname(
    os.path.abspath(__file__))).parent.parent)
print(MEDOMICS_WS)
cwd = os.getcwd()
isFrontSlash = cwd.find("/")
if os.getcwd().find("/") == -1:
    MEDOMICS_WS = MEDOMICS_WS.replace("/", "\\")

# blueprint definition
app_learning = Blueprint('app_learning', __name__,
                         template_folder='templates', static_folder='static')

# global variables
experiments = {}
cur_dashboard = None
files_uploaded = []
df = []


@app_learning.route("/run_experiment", methods=["POST"])
def run_experiment():
    """
    triggered by the button play in the dashboard, it starts the execution of the pipeline

    Returns: the results of the pipeline execution
    """
    json_config = get_json_from_request(request)
    print("received data from topic: /run_experiment:")
    print(json.dumps(json_config, indent=4, sort_keys=True))
    scene_id = json_config['scene_id']
    global experiments
    experiment = copy.deepcopy(
        experiments[scene_id]) if scene_id in experiments else None
    try:
        if experiment is None:
            experiment = MEDexperiment(json_config)
        else:
            experiments[scene_id].update(json_config)
        experiments[scene_id].start()
        results_pipeline = experiments[scene_id].get_results()
        json.dumps(results_pipeline)
    except BaseException as e:
        return get_response_from_error(e)

    return results_pipeline


@app_learning.route('/progress', methods=['POST'])
def progress():
    """
    triggered each x millisecond by the dashboard, it returns the progress of the pipeline execution

    Returns: the progress of the pipeline execution

    """

    global experiments
    json_config = get_json_from_request(request)

    if json_config['scene_id'] in experiments:
        return experiments[json_config['scene_id']].get_progress()
    else:
        return {'cur_node': '', 'progress': 0}


@app_learning.route('/code_generation', methods=['POST'])
def code_generation():
    """
    Returns: the code generated by the pipeline execution
    """

    json_config = get_json_from_request(request)
    print("received data from topic: /code_generation:")
    print(json.dumps(json_config, indent=4, sort_keys=True))

    global experiment
    try:
        if experiment is None:
            experiment = MEDexperiment(json_config)
        else:
            experiment.update(json_config)
        experiment.generate_code()
        return experiment.get_results()

    except BaseException as e:
        return get_response_from_error(e)
